app: tulip-shop-tavern
component: aws-dynamodb
name: database

inputs:
  name: ${name}-${stage}
  region: us-east-1
  # Don't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  # Simple, single-table design
  attributeDefinitions:
    - AttributeName: hk
      AttributeType: S
    - AttributeName: sk
      AttributeType: S
    - AttributeName: sk2
      AttributeType: S
  keySchema:
    - AttributeName: hk
      KeyType: HASH
    - AttributeName: sk
      KeyType: RANGE
  globalSecondaryIndexes:
    - IndexName: gsi1
      KeySchema:
        - AttributeName: sk2
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: tulipshoptavern.chrisubick.io
    basePath: ''
    createRoute53Record: true
